# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sclkq-gwOW6KtR1gOfr9Dt_bLnhuIZJP
"""

#INHERITANCE
#SINGLE INHERITANCE
class parent:
  def __init__(self,name):
    self.name=name
  def greet(self):
    print(f"hello,{self.name}")
class child(parent):
   def __init__(self,name,age):
    super().__init__(name)
    self.age=age
   def display_age(self):
    print(f"{self.name} is {self.age}years old")
c1= child("Bob",20)
print(c1.name)
print(c1.age)
c1.greet()
c1.display_age()

#MULTILEVEL INHERITANCE
class A:
  def display(self):
    print("class A")
class B:
  def show(self):
    print("class B")
class C(A,B):
  def display(self):
    print("class C")
class D(C):
  def display(self):
    print("class D")
    super().display()
    super(C,self).show()
    A.display(self)
d=D()
d.display()

